sudo: false
language: rust
env:
  global:
  - CRATE_NAME=efficio-server
matrix:
  include:
  - env: TARGET=x86_64-unknown-linux-gnu 
    script: cargo build; cargo build --release; cargo test
  # - env: TARGET=x86_64-apple-darwin
  #   os: osx
  # - env: TARGET=x86_64-pc-windows-msvc
  #   os: windows
  # - env: TARGET=x86_64-unknown-linux-gnu
  #   rust: beta
  # - env: TARGET=x86_64-unknown-linux-gnu
  #   rust: nightly
  # - env: RUSTFMT
  #   rust: stable
  #   install:
  #   - rustup component add rustfmt
  #   script:
  #   - cargo fmt -- --check
  # - env: RUSTFLAGS="-D warnings"
  #   rust: stable
  #   install: 
  #   script:
  #   - cargo check --tests
  # - env: CLIPPY
  #   rust: stable
  #   install:
  #   - rustup component add clippy
  #   script:
  #   - cargo clippy --all-features
install:
- rustc -Vv
- cargo -V
- curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $TRAVIS_RUST_VERSION
- source ~/.cargo/env || true
branches:
  only:
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
  - master
before_deploy:
  - sh ci/before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: lmz5PtbDLE2MgwYD4Q1pIvKb+tFVEFiZmUVg4SFPRwSHEFjgOhmkQRFcqBP3Kom1mnf2DOTm6aGmnej1lkHtZmbwe2a5VOwPzdaqQcr7t2pRv2bgzzQF+Ofvqq5+vNpXfy3QQHsdZzUJOH86l6AwYm044n3xj6jJkXOSqhcT4IoySDhVBUPsg8l/MRYIjgtmGdam7FD8EfVNry0M8W1VYQJ+ELt/gSg5SjIWavMLmFcx6PRy/0IUvEOfIUNPoNbXxAWNW9uUW2QRxi/jjRew4XDKCVr4OLlbtSDm8jvnl38xhUmG1C02cbO+Wc8TDjnSPc+H1q6VfTHdj9kzXQZVRmN6mv3WYBkHcuMZtYWaw3wr2YcUOV0bT76o21oV5NPuLY2H1YFm0p+OarKmu1PRu3qoR6f78eaxWZlxFiuExIYsOKgIkf2iVaH02Q8J3dp7r/qdlbb5CpQGiYx7n2uGFgdi6icCkdTo/Ds6YLdlkolbupgamMKU5N9eLyLiMrzC13oTOV7kpk0+KVkeqQWkgqQxSurlAbRkiqlVkYXhylwNP1s/PktjSy8oL7cHqUw3JFqy+5K1PsVBS+6jATAWVIoPD/1HAYpbAAOvqVqjvXqi2DH5hcrovVY1fergGKrG2gZzZRpVVlg2sWYxziQErkrAzyFnS9R2DkmmRku3YwY=
  file: $CRATE_NAME.tar.gz
  skip_cleanup: true
  on:
    condition: "$TRAVIS_OS_NAME = linux && $TRAVIS_RUST_VERSION = stable"
    repo: ghost-in-the-sushi/efficio-server
cache:
  cargo: true
before_cache:
- chmod -R a+r $HOME/.cargo
notifications:
  email:
    on_success: never
