sudo: false
language: rust

env:
  global:
  - CRATE_NAME=efficio-server

matrix:
  include:
  # Linux
  - env: TARGET=x86_64-unknown-linux-gnu

  # OSX
  - env: TARGET=x86_64-apple-darwin
    os: osx

  # Testing other channels
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: beta
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: nightly

  - env: COVERALLS=0.0.9
    install:
    - travis_wait cargo install cargo-travis --force --vers $COVERALLS
    script:
    - cmake --version
    - cargo coverage || true
  - env: RUSTFMT
    rust: 1.34.2  # `stable`: Locking down for consistent behavior
    install:
    - rustup component add rustfmt
    script:
    - cargo fmt -- --check
  - env: RUSTFLAGS="-D warnings"
    rust: 1.34.2  # `stable`: Locking down for consistent behavior
    install:
    script:
    - cargo check --tests
  - env: CLIPPY
    rust: 1.34.2  # `stable`: Locking down for consistent behavior
    install:
      - rustup component add clippy
    script:
      - cargo clippy --all-features

install:
- rustc -Vv
- cargo -V
- curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $TRAVIS_RUST_VERSION
- source ~/.cargo/env || true

script:
- cargo test --verbose
- cargo test --verbose --no-default-features

before_deploy:
- sh ci/before_deploy.sh

branches:
  only:
  # Release tags
  - /^v\d+\.\d+\.\d+.*$/
  - master

addons:
  apt:
    packages:
    # necessary for `cargo coveralls`
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
    - cmake

cache:
  apt: true
  cargo: true
before_cache:
# Travis can't cache files that are not readable by "others"
- chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
  # webhooks:
  #   urls:
  #   - https://webhooks.gitter.im/e/7e08f15b115326957c31
  #   on_success: change  # options: [always|never|change] default: always
  #   on_failure: always  # options: [always|never|change] default: always
  #   on_start: never     # options: [always|never|change] default: always
