[package]
name = "efficio-server"
version = "0.1.0"
authors = ["Geobert Quach <geobert@protonmail.com>"]
edition = "2018"

[dependencies]
fake_redis = { path = "libs/fake_redis" }
warp = "0.1.15"
structopt = "0.2.15"
redis = "0.10.0"
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"
serde_repr = "0.1.4"
failure = "0.1.5"
rand = "0.6.5"
argon2rs = "0.2.5"
lazy_static = "1.3.0"
hex-view = "0.1.2"
validator = "0.8.0"
validator_derive = "0.8.0"
zxcvbn = "1.0.1"
regex = "1.1.6"
derive_deref = "1.0.2"
derive-new = "0.5.6"
r2d2 = "0.8.4"
r2d2_redis = "0.9.0"
log = "0.4.6"
pretty_env_logger = "0.3.0"




